---
- name: Setup Counter Strike Global Offensive server
  hosts: cs_servers
  vars:
    # CS:GO Token can be retrieved here: https://steamcommunity.com/dev/managegameservers (Game ID 730)
    csgo_token: XXXXXXXXXXXXXXXXXXXXXXXXXXX
    # Web API Token can be retrieved here: https://steamcommunity.com/dev/registerkey
    csgo_web_api_token: XXXXXXXXXXXXXXXXXXXXXXXXXXX
    
  roles:
    - aubruz.steamcmd
    - aubruz.csgo_server
