---
- name: Run user setup
  import_playbook: setup_users.yml

- name: Run system
  import_playbook: setup_system.yml

- name: Install CSS and CS:GO
  hosts: cs_servers
  vars:
    # CS:GO Token can be retrieved here: https://steamcommunity.com/dev/managegameservers (Game ID 730)
    csgo_token: XXXXXXXXXXXXXXXXXXXXXXXXXXX
    # Web API Token can be retrieved here: https://steamcommunity.com/dev/registerkey
    csgo_web_api_token: XXXXXXXXXXXXXXXXXXXXXXXXXXX

  roles:
    - role: aubruz.steamcmd
    - role: aubruz.css_server
      css_port: 27015
    - role: aubruz.csgo_server
      csgo_port: 27014
