---
- name: Setup users and keys
  hosts: cs_servers
  gather_facts: False
  vars:
    - steam_user: steam
    - super_user: centos
    - users:
        - name: {{ super_user }}
          key: "~/.ssh/mykey.pub" # Don't forget to modify this with your own key
          groups: wheel # sudo for Ubuntu/Debian
          system: False
          shell: /bin/bash

        - name: "{{ steam_user }}"
          key: False
          groups: []
          system: True
          shell: /sbin/nologin

  tasks:
    - name: Add users
      user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
        system: "{{ item.system }}"
        shell: "{{ item.shell }}"
      loop: "{{ users }}"

    - name: Add keys to autohrized_key
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file',  item.key) }}"
      loop: "{{ users }}"
      when: item.system == False
